export default [
  {
    appName: `Best Seller Searcher`,
    imageLink: `bestSellerSearcher.jpg`,
    deployLink: `https://dry-wave-20540.herokuapp.com/`,
    repoLink: `https://github.com/mczuckermann/BestSellerSearcher`,
    shortBio: `React, Node.js, Express.js, Passport.js, MongoDB, Mongoose`,
    projectRole: `Authentication // API // Back-End Developer`,
  },
  {
    appName: `Snippets`,
    imageLink: `codesnippetsScreenShot.jpg`,
    deployLink: `https://morning-harbor-79094.herokuapp.com/home`,
    repoLink: `https://github.com/mczuckermann/CodeSnippets`,
    shortBio: `Handlebars, Javascript, Node.js, Express.js, Passport.js, MySQL, Sequelize`,
    projectRole: `Authentication // Front-End Developer`,
  },
  {
    appName: `Music Portfolio`,
    deployLink: `https://jz-development.netlify.com/`,
    repoLink: `https://github.com/mczuckermann/jz-music-portfolio`,
    shortBio: `React, Gatsby, GraphQL, Cloudinary, Typescript, Jest`,
    projectRole: `Sole Developer`,
  },
  {
    appName: `Store Stock`,
    imageLink: `storestockScreenShot.jpg`,
    deployLink: `https://www.youtube.com/watch?v=uQq6YGy_8hs`,
    repoLink: `https://github.com/mczuckermann/Store-Stock-Item-Grabber_MySQL-Node`,
    shortBio: `Javascript, Node.js, MySQL`,
    projectRole: `Sole Developer`,
  },
  {
    appName: `Friend Finder`,
    imageLink: `friendScreenShot.jpg`,
    deployLink: `https://friend-finder-zuckermann.herokuapp.com/`,
    repoLink: `https://github.com/mczuckermann/Friend-Finder_Express-Node-Javascript`,
    shortBio: `JavaScript`,
    projectRole: `Sole Developer`,
  },
  {
    appName: `Liri Bot`,
    imageLink: `liribotScreenShot.jpg`,
    deployLink: `https://www.youtube.com/watch?v=8cOBg6EDE40`,
    repoLink: `https://github.com/mczuckermann/Liri-Bot_Node-Javascript-RestAPIs`,
    shortBio: `JavaScript, Node.js`,
    projectRole: `Sole Developer`,
  },
]
